### ISSUE TITLE
Rendering is borked in the current master

### ISSUE THREAD

**Issue by motorsep** [eXistence/fhDOOM#18]
Finally built the engine, but now when I run it, rendering is completely broken:

https://www.youtube.com/watch?v=yYEi_A9vw4U

I am Windows 10 64bit Home, i3-6100, 16Gb RAM, GF 1060 GTX 6Gb, Nvidia 390.65 driver.

All other OpenGL games work fine, including vanilla Doom 3.

**Comment by eXistence** [comment]
hmmmm... this is basically what fhDOOM is doing? fhDOOM comes with 5 pk4 files (and the binaries):
-  pak005.pk4
-  pak006.pk4
-  pak007.pk4  
-  pak008.pk4
-  pak100fhdoom.pk4
 
The pak00x.pk4 files are just the additional pk4 files from the latest Doom3 patch (1.3.1 IIRC). These files should also be identical to the files distributed via Steam. No need to overwrite.

pak100fhdoom.pk4 contains all the updated and added files required by fhDOOM. Of course this file is not part of the git repository. In the repo all the updated and added files are stored loosely in the base directory, so its easy to modify them as a developer.
There is a special build target called 'dist' (you should see it in visual studio), that collects these files and generates the pk4 file and packages everything up into a nicely distributable zip file for release.

Maybe the root of all your problems is the way you 'installed' fhDOOM. In your video it looks like you copied some (all?) fhDOOM files into an existing Doom3 installation (from Steam). If done correctly this could work, but it is not the way it is meant to be installed and i never test that. fhDOOM needs only 5 files from the original game: pak000.pk4 - pak004.pk4. Just copy these files from the original Doom3 (CD or Steam) to the fhDOOM directory (don't do it the other way round, don't install fhDOOM into an existing Doom3 installation). This way you get a clean installation. This is also the way described on the github page (https://github.com/eXistence/fhDOOM#installation), but maybe i should make it more clear...

Btw: for development it is exactly the same: just copy the 5 pak00[0-4].pk4 files into the cloned git repository (git will ignore them). Compiled exe can be directly started, it will pick up the base path and game dll automatically. It will use all the loosely files stored in the base directory directly (packaging them up into a pk4 not needed for  development). No need for constantly copying or packaging files. 
Btw2: There are a couple of things on the master branch that are not finished yet or currently broken... just as a warning :)

Hope that helps :)

**Comment by motorsep** [comment]
Well, what's the point of including pak005.pk4 - pak008.pk4 (since Steam install has those and even retail installs, if anyone still uses original CDs would have all the patches installed by now) ? If all the fhDoom changes/additions are in pak100fhdoom.pk4 then it just makes it more confusing for end-users. That's what got me when I was copying over files - I wasn't sure if I need to skip those or overwrite those pk4s.

The way I used to deal with all the idTech forks (Darkplaces, RBDoom 3 BFG, etc. ) is I'd either copy newly built .exe into game's root folder and run it (Darkplaces) or copy unpacked shaders into base/ and .exe into root and run it (RBDoom 3 BFG).

Either way, it is what it is and I got it up and running :) Thanks.

**Comment by eXistence** [comment]
When i started to work on fhDOOM, these were my requirements:
 * easy to run from code directory
 * easy to debug from Visual Studio
 * easy editing of all files
 * no copying or packaging of files (after making a build)
 * no files in source control, that can be easily generated
 * minimal install, no files that fhDOOM does not need
 * no need to download and install latest Doom3 patch
 * no need to run WindowsXP-era setups to install or patch the game

I am sure there are other solutions out there, but the current setup has served me quite well so far.
Of course you are right about the last two requirements, they are totally irrelevant for people that have a 
patched version of Doom3 installed or installed the game via Steam. 

You are the first reporting issues with the installation procedure, so thx for that, because i never gave it much thought. I improved the description on installing and building fhDOOM, but people still have to read it...

Next release might come in variant without the files from the 1.31 patch.
